### PR TITLE
Add support for substitution type and internal utility types

### LINKED ISSUE #2: `Unknown type parameter K` for typescript internal utilities
Give this test file:

```ts
export type A = {
    foo: 'bar';
    bar: string;
};
export type B = Omit<A, 'foo'>;
```

The package will throw an error like:

```bash
Error: Unknown type parameter K
    at Context.getType (/Users/mirone/Code/unplugin-tsdoc/node_modules/.pnpm/getdocs-ts@0.1.4/node_modules/getdocs-ts/src/index.js:179:23)
    at Context.getTypeParam (/Users/mirone/Code/unplugin-tsdoc/node_modules/.pnpm/getdocs-ts@0.1.4/node_modules/getdocs-ts/src/index.js:454:62)
    at Context.getType (/Users/mirone/Code/unplugin-tsdoc/node_modules/.pnpm/getdocs-ts@0.1.4/node_modules/getdocs-ts/src/index.js:213:67)
    at Context.itemForSymbol (/Users/mirone/Code/unplugin-tsdoc/node_modules/.pnpm/getdocs-ts@0.1.4/node_modules/getdocs-ts/src/index.js:96:22)
    at Context.gatherSymbols (/Users/mirone/Code/unplugin-tsdoc/node_modules/.pnpm/getdocs-ts@0.1.4/node_modules/getdocs-ts/src/index.js:28:47)
    at /Users/mirone/Code/unplugin-tsdoc/node_modules/.pnpm/getdocs-ts@0.1.4/node_modules/getdocs-ts/src/index.js:692:125
    at Array.map (<anonymous>)
    at gatherMany (/Users/mirone/Code/unplugin-tsdoc/node_modules/.pnpm/getdocs-ts@0.1.4/node_modules/getdocs-ts/src/index.js:675:18)
    at gather (/Users/mirone/Code/unplugin-tsdoc/node_modules/.pnpm/getdocs-ts@0.1.4/node_modules/getdocs-ts/src/index.js:665:12)
    at file:///Users/mirone/Code/unplugin-tsdoc/demo.js:12:15
```

Additional information:

I found out that the `maybeDecl(type.symbol)?.parent?.kind` is equal to `SyntaxKind.TypeAliasDeclaration` here.

```ts
    if (type.flags & TypeFlags.TypeParameter) {
      let name = type.symbol.name, found = this.typeParams.find(p => p.name == name)
      if (!found && maybeDecl(type.symbol)?.parent?.kind != SyntaxKind.InferType)
        throw new Error(`Unknown type parameter ${name}`)
      return {type: name, typeParamSource: found ? found.id : this.id}
    }
```

### PR DESCRIPTION
**Pull request by Saul-Mirone**
Closes: #2

### CODE REVIEW

**Comment by marijnh** [comment]
`typeParamSource` is expected to hold a local item ID, so putting a path in there will make the doc generator emit nonsense.

Also, what kind of type gets the `Substitution` flag?

**Comment by Saul-Mirone** [comment]
The problem is that typescript will try to unwrap something like `Omit` and replace it with `Pick` implementation. I didn't find a good way to represent it.

I don't know the implementation details of `Substitution` flag, but if you run `getdocs-ts` with following code, it will create use that flag:
```
import { defineComponent } from vue;

export const a = defineComponent;
```

Maybe instead of throw errors, we can let users to pass in some options to handle the unknown types?

**Comment by marijnh** [comment]
The representation of these kind of types seems pretty bizarre — no type with the name `Omit` appears anywhere. Instead the `target` property of the type holds `Pick<T, K>`, but those parameters aren't even defined there. The only place where TS seems to hold this information is the syntax parse tree, but reconstructing types from that in a general way would require us to write logic for every syntax node kind, which doesn't seem like a reasonable direction to go in.

I'll see if I can special case straightforward alias declarations where the type is simply a named type with parameters.

**Comment by Saul-Mirone** [comment]
I agree. I think trying to construct the correct representation for complex types is not very useful. I'd rather keep the name of the type and add some comments on it.

The problem stop me using this package is that it will just throw errors for the type cannot be analyzed. It would be great if we can have some kind of common representation for this case.

**Comment by marijnh** [comment]
Patch 3911b490d47f3f12083e5e35f812de59aa3a478f adds a (disturbingly special-cased) solution for the `Omit` test case. b3d51a4055be18d6520f5c9f703414408be20b7f adds support for template literals (including their arguments). Does that help?

**Comment by Saul-Mirone** [comment]
I'll test the package with `defineComponent` in vue to see if everything works fine.

**Comment by Saul-Mirone** [comment]
👍 Works perfectly now.

**Comment by Saul-Mirone** [comment]
Closing since the solution is not good enough.

**Pull request closed without merging**
